// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YazilimPark.Models;

namespace YazilimPark.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220517065910_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("YazilimPark.Models.RandomQuotations", b =>
                {
                    b.Property<int>("RQ_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Quotation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RQ_ID");

                    b.ToTable("RandomQuotations");
                });
#pragma warning restore 612, 618
        }
    }
}
